repos:
  - repo: local
    hooks:
      - id: hatch-lint-check
        name: Hatch Lint Check
        entry: hatch
        args: ["run", "lint-check"]
        language: system
        types: [python]
